export const SITE_URL = "https://www.robinzone.ai";

export const SITE_LINKS = {
  home: `${SITE_URL}/`,
  dashboard: `${SITE_URL}/dashboard`,
  models: `${SITE_URL}/models`,
  imageModels: `${SITE_URL}/models?type=image`,
  videoModels: `${SITE_URL}/models?type=video`,
  assist: `${SITE_URL}/assist`,
  create: `${SITE_URL}/create`,
  creations: `${SITE_URL}/dashboard?tab=creations`,
  login: `${SITE_URL}/login`,
  creationStudio: `${SITE_URL}/creation-studio`,
  pricing: `${SITE_URL}/pricing`,
  helpCenter: `${SITE_URL}/help-center`,
  about: `${SITE_URL}/about`,
  careers: `${SITE_URL}/careers`,
  contact: `${SITE_URL}/contact`,
  cancelSubscription: `/cancel-subscription`,
  privacy: `${SITE_URL}/legal/privacy`,
  terms: `${SITE_URL}/legal/terms`,
  cookies: `${SITE_URL}/legal/cookies`,
  refund: `${SITE_URL}/legal/refund`,
  billing: `${SITE_URL}/legal/billing`,
  help: "https://help.robinzone.ai/",
  reviews: `${SITE_URL}/reviews`,
  growthTracking: `${SITE_URL}/#features`,
  audienceInsights: `${SITE_URL}/#features`,
  hiddenInteractions: `${SITE_URL}/#features`,
  followersUnfollowers: `${SITE_URL}/#features`,
  contentPerformance: `${SITE_URL}/#features`,
  support: "mailto:support@robinzone.ai",
};
