/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GatedRouteImport } from './routes/_gated'
import { Route as GatedIndexRouteImport } from './routes/_gated.index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ApiColorGradeRouteImport } from './routes/api/color-grade'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicErrorsReportRouteImport } from './routes/api/public/errors/report'

const GatedRoute = GatedRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedIndexRoute = GatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GatedRoute,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiColorGradeRoute = ApiColorGradeRouteImport.update({
  id: '/api/color-grade',
  path: '/api/color-grade',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicErrorsReportRoute = ApiPublicErrorsReportRouteImport.update({
  id: '/api/public/errors/report',
  path: '/api/public/errors/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GatedIndexRoute
  '/api/color-grade': typeof ApiColorGradeRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/api/public/errors/report': typeof ApiPublicErrorsReportRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/api/color-grade': typeof ApiColorGradeRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/': typeof GatedIndexRoute
  '/api/public/errors/report': typeof ApiPublicErrorsReportRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_gated': typeof GatedRouteWithChildren
  '/api/color-grade': typeof ApiColorGradeRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/_gated/': typeof GatedIndexRoute
  '/api/public/errors/report': typeof ApiPublicErrorsReportRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/color-grade'
    | '/legal/$slug'
    | '/api/public/errors/report'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/color-grade'
    | '/legal/$slug'
    | '/'
    | '/api/public/errors/report'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/_gated'
    | '/api/color-grade'
    | '/legal/$slug'
    | '/_gated/'
    | '/api/public/errors/report'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GatedRoute: typeof GatedRouteWithChildren
  ApiColorGradeRoute: typeof ApiColorGradeRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ApiPublicErrorsReportRoute: typeof ApiPublicErrorsReportRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/': {
      id: '/_gated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GatedIndexRouteImport
      parentRoute: typeof GatedRoute
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/color-grade': {
      id: '/api/color-grade'
      path: '/api/color-grade'
      fullPath: '/api/color-grade'
      preLoaderRoute: typeof ApiColorGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/errors/report': {
      id: '/api/public/errors/report'
      path: '/api/public/errors/report'
      fullPath: '/api/public/errors/report'
      preLoaderRoute: typeof ApiPublicErrorsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GatedRouteChildren {
  GatedIndexRoute: typeof GatedIndexRoute
}

const GatedRouteChildren: GatedRouteChildren = {
  GatedIndexRoute: GatedIndexRoute,
}

const GatedRouteWithChildren = GatedRoute._addFileChildren(GatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GatedRoute: GatedRouteWithChildren,
  ApiColorGradeRoute: ApiColorGradeRoute,
  LegalSlugRoute: LegalSlugRoute,
  ApiPublicErrorsReportRoute: ApiPublicErrorsReportRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
